name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: gpt-4o
      OPENAI_TEMPERATURE: "0.8"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify environment and imports
        run: |
          python - <<'PY'
          import os
          assert os.getenv('OPENAI_API_KEY'), 'OPENAI_API_KEY not set in env'
          import streamlit, openai
          print('streamlit', streamlit.__version__)
          print('openai', getattr(openai, '__version__', 'legacy'))
          print('OK')
          PY

